### ISSUE TITLE
[ENH] - 1d and 2d function compatibility

### ISSUE THREAD

**Issue by maestapereira** [spiketools/spiketools#101]
Make functions allow for 1d and 2d positions, bins, and edges. 
The goal is to reduce unnecessary overlapping code.
PR #102 

1. spatial\occupancy.py
- [x] `compute_spatial_bin_edges`
- [x] `compute_spatial_bin_assignment`
- [x] `compute_occupancy`
2. spatial\utils.py
- [x] `get_pos_ranges` (also added example/docstring test for this one)

**Comment by TomDonoghue** [comment]
Done in #102
