### ISSUE TITLE
[BUG] - Array orientation for 2d position with a single datapoint

### ISSUE THREAD

**Issue by maestapereira** [spiketools/spiketools#162]
If both following conditions are satisfied:
* there is only one 2d `position` data point in row orientation (`position.shape == (2, 1)`)
* the orientation is not specified as an input to `spiketools.spatial.utils.get_position_xy`

There is an error when `spiketools.spatial.utils.get_position_xy` tries to imply the orientation.
This happens because `check_array_orientation(arr)` returns `'column'` when it should return `'row'`.
This is due to the condition `position.shape[-2] > position.shape[-1]` in `check_array_orientation(arr)`, which yields `'column'` as an output. This output is usually correct, but for the case of `position.shape == (2, 1)`, it is not.

I assume this happens with all other functions that imply the orientation if the `position` input has `position.shape == (2, 1)`, but I have not checked.

**Comment by TomDonoghue** [comment]
This is now addressed in #186 - I'm going to close this here to move any further discussion there.
