### ISSUE TITLE
[ENH] - Add randomness to `shuffle_poisson`

### ISSUE THREAD

**Issue by maestapereira** [spiketools/spiketools#163]
Opening one full issue for item 7 of #159 

**Context**: The `shuffle_poisson` function is just permutations of one spike train. 
In the source code of `shuffle_poisson`, we have `isis = permute_vector(compute_isis(poisson_spikes), n_permutations=n_shuffles)` and `permute_vector` says that there is no randomness - the permutation is just moving an ISI and a spike from the end to the beginning. 

**Issue**: If your `num_shuffles` is small, then your random permutations will be very similar to each other while being quite different from the original data. Therefore, this would  not serve as a good baseline distribution for stats. 

Recommendation from @rly to address this issue by doing one of the following: 
1. Add a warning about this behavior in the `shuffle_poisson` documentation
2. Introduce randomness such that `poisson_generator` is called once for each shuffle instead of just once to introduce randomness in `permute_vector`.

**Comment by TomDonoghue** [comment]
These topics have now been addressed in #183 - closing this here now!
