### ISSUE TITLE
[BUG] - Issue with `create_spike_train`

### ISSUE THREAD

**Issue by maestapereira** [spiketools/spiketools#75]
There is an issue with the `create_spike_train` function, in that it sometimes ignores the last spike time. 
This affects `shuffle_circular` and `shuffle_bins` functions. Might be one cause of #5 

Example:
```
spikes = np.array([ 5, 91, 186, 206, 236, 325, 378, 677, 720, 763])
spike_train = create_spike_train(spikes)
# check that the last spike is missing by the following line:
np.where(spike_train)
```

This seems to be happening because the pre-allocated space for the output (`spike_train`) in the `create_spike_train` is too small by one. Additionally, when setting `1` to the correct `spike_train` positions, the last one is missing.

ToDo:
- [x] create PR to fix it (Sandra) #76

**Comment by TomDonoghue** [comment]
Great catch @maestapereira! I've merged your PR (#76), so this should be addressed now, so I'll close this now! Feel free to re-open if there is anything else here.
